### ISSUE TITLE
Question regarding manifold alignment 

### ISSUE THREAD

**Issue by peekxc** [ericjang/genadv_tutorial#7]
Hi Eric, 

I really enjoyed this tutorial! I do have one question about the manifold alignment part, though. 

This concept of aligning the two manifolds seems to be quite important indeed, [and several authors are investigating it more in depth](https://arxiv.org/pdf/1710.11260.pdf). 

In this example, I'm a little unsure how the sorting works. Namely, I thought the goal in minimizing the transformation distance from Z to X would require changing the initial weights of the generator such that the 'ordering' of z inputs to x output is (loosely) as monotonic as possible, assuming one has a definition of ordering. 

So my understanding was that each specific input **z_i** corresponds to its specific generated pair **x_i** = G(**z_i**), and the goal was to make this relationship as monotonic as possible. But you don't keep this correspondence, right? You generate a set of **x_i**'s from a sampled batch of **z_i**'s and force the ordering, but isn't this artificial? I don't see why this would actually align the latent z-space and the X space?

**Comment by ericjang** [comment]
Right, the correspondence is not so strict as to preserve x_i = G(z_i) where G is a monotonically increasing function w.r.t. z_i, since this would require that x_i are still well-ordered *between* stochastic minibatches.

It's helpful to think of this in the situation where the minibatch size approaches infinity, which is practically the case for a simple transformation from a 1-D uniform to a 1-D Gaussian. 

A G function that can map G(z_1) < G(z_3) < G(z_2) for z_1 < z_2 < z_3 will be forced to express a non-monotonic function, which has higher polynomial degree (a proxy for complexity) than a simple monotonic or even linear one. In order to minimize "distortion" in the function that G must learn, I am taking advantage of the fact that I know the transformation is simpler when the input and outputs are well-ordered.

If one desires an explicit correspondence (e.g. for low minibatch sizes), stratified sampling would work too. 

Please feel free to re-open the issue if you have further questions!
